### ISSUE TITLE
Policy not referencing correct Kernels

### ISSUE THREAD

**Issue by MatthiasL-SAP** [SAP-samples/frun-csa-policies-best-practices#19]
https://github.com/SAP-samples/frun-csa-policies-best-practices/blob/d6e2b8ecf82067598feee55214422a94ce5b9d41/NotesPolicies/ABAP/ABAP_snotes_patchday_2021/ABAP_snotes_patchday_2021-11.xml

Note 0003080567 

This note incorrectly references less Kernel and their correct SP/PL than are mentioned in the note. For example, 7.53 isn't there and could for example be copied from earlier patchday with the same note:
https://github.com/SAP-samples/frun-csa-policies-best-practices/blob/e67b29c3648736707073642f25123893ca43b774/NotesPolicies/ABAP/ABAP_snotes_patchday_2021/ABAP_snotes_patchday_2021-09.xml

**Comment by ManfredAch** [comment]
when we defined the policy 2021 there was no solution available for several kernel releases:
"for other kernel releases no fix offered, please read the note 3099776"
In april 2022 there was an update of the note and we decided not to check this note as it is 
not related to ABAP, but webdispatcher
only relevant, if certain conditions fullfilled.
Because of this we do not update the policy.
